import { User } from './user';

export const USERES: User[] = [
  { id: 11, name: 'Dr Nice', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 12, name: 'Narco', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 13, name: 'Magneta', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 14, name: 'Bombasto', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 15, name: 'RubberMan', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'',  hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 16, name: 'RubberMan', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 17, name: 'RubberMan', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 18, name: 'RubberMan', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567', 
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 19, name: 'RubberMan', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 20, name: 'Hydrogen', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 21, name: 'Helium', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 22, name: 'Lithium', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 23, name: 'Boron', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 24, name: 'Tornado', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
   subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 25, name: 'Magma', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 26, name: 'Dr IQ', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
  { id: 27, name: 'Dynama', email: 'abc@gmail.com', password: '1111111',gender: 1, phoneNumber:'1234567',
    subject:'', hobbies: 'sing', dateOfBirth: new Date(), note: ''},
];